site_name: My Docs

theme:
  name: 'material'
  features:
    - content.code.copy
    - content.tabs.link
    - content.action.edit
    - content.action.view
  language: 'ja'


extra:
    search:
        language: 'ja'

          
plugins:
  - i18n:
      default_language: ja
      docs_structure: suffix
      languages:
        ja:
          name: 日本語
          build: true
        en:
          name: English
          build: true
  - search
  - table-reader




    

markdown_extensions:
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.highlight
    - pymdownx.keys
    - tables
    - attr_list
    - md_in_html
    - pymdownx.magiclink
    
nav:
    - Home: index.md
    - サンプル:
        - サンプル1:
            - サンプル1-1: hogehoge.md
    - 🌍 GitHub Pages で MkDocs サイトを公開する手順: github_pages.md
    - 📌 Githubの基本的な使い方: HowToUseGithub.md





extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/highlight.min.js
    - javascripts/config.js
extra_css:
    - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.1/styles/default.min.css



